name: Deploy static content to Pages

on:
  push:
    branches: ["main"]   # deploy on push to main
  workflow_dispatch:      # allow manual run

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./           # this uploads EVERYTHING in repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
